<?php

namespace OLOG\PageRegions;

class Permissions
{
    const PERMISSION_PAGEREGIONS_MANAGE_BLOCKS = 'PERMISSION_PAGEREGIONS_MANAGE_BLOCKS';
    const PERMISSION_SEE_ADMIN_BLOCKS = 'PERMISSION_SEE_ADMIN_BLOCKS';
}